### PR TITLE
Ignore nils in child elements list

### PR DESCRIPTION
**Pull request by drozdoff**

### CODE REVIEW

**Comment by joshnuss** [comment]
Hi @drozdoff,

Thinking about it, I'm not 100% sure if `nil` elements should be handled at the library level, since nils can be filtered out before calling the lib.

Can you describe your use case?

**Comment by drozdoff** [comment]
Hello @joshnuss!

I quite often find myself in situations like this: 
`element(:nodes, [:one, :two, nil, :four])`

and get the XML like this:

`<node><one/><two/></><four/></node>`.

I understand, that nil filtering may be done outside of the library, but I don't think that `</>` tag is useful for anyone in any case. So I thought, maybe It makes sense to just filter it out inside the library and save some effort to library users.

Thank you!

**Comment by joshnuss** [comment]
I see, thanks for clarifying. 

Yeah, makes sense to add since it will improve the current experience.

**Comment by joshnuss** [comment]
Thanks @drozdoff!!

**Pull request merged**
