### PR TITLE
CI build with Elixir 1.6 - 1.11

### PR DESCRIPTION
**Pull request by devstopfix**
Removed OTP version from build to allow Elixir 1.6, the last supported Elixir version

(replaces similar earlier PR which got corrupted)

### CODE REVIEW

**Comment by devstopfix** [comment]
Apologies for the noise on this PR - I messed up the first git commit, can't get Travis to see my fork, and Travis is throttled in general so the builds take hours!  Hopefully the last commit will pass

**Comment by joshnuss** [comment]
No worries. Looks like it's passing now.
I probably should switch to GH actions one day.
Thanks again James! Much appreciated

**Comment by devstopfix** [comment]
Yes I just made the switch this weekend!  https://github.com/devstopfix/xml_builder/blob/master/.github/workflows/elixir.yml

**Comment by joshnuss** [comment]
Perfect, I will copy that :+1:

**Pull request merged**
