### PR TITLE
Access implementation.

### PR DESCRIPTION
**Pull request by am-kantox**
This PR provides an implementation of [`Access`](https://hexdocs.pm/elixir/Access.html) behaviour for raw (tuples) representation of XML.

It is handy to access deeply nested elements as well as building the deeply nested documents automatically.

### CODE REVIEW

**Comment by joshnuss** [comment]
Thanks @am-kantox, cool idea!
I will give it a test and add some comments.

**Comment by joshnuss** [comment]
And can you provide a use case? 
Since until now `xml_builder` was about generating xml, I wonder if it's worth adding traversing logic, or maybe it should be a separate thing, not sure.

**Comment by am-kantox** [comment]
It is not about traversing. Imagine I have XML generated and then I want to add a child deeply inside.

**Comment by joshnuss** [comment]
I see, but generating XML is usuallt based on an underlying data structure or assembly pipeline, couldn't the child data be added there, instead of creating a doc and then patching it?

Maybe this would be good as a separate package? I'd prefer to keep the surface area of this repo as small as possible.

**Comment by joshnuss** [comment]
@am-kantox thanks for the contribution.

I encourage you to create a package for this as it could be helpful to some.

Appreciate your work on this!

**Comment by am-kantox** [comment]
FWIW, here is the package: https://hexdocs.pm/xml_builder_access

**Pull request closed without merging**
