### PR TITLE
Full UTF-8 xml declaration

### PR DESCRIPTION
**Pull request by remiq**
Declaration<?xml version="1.0"> is not correct and will not work with :xmerl.

### CODE REVIEW

**Comment by joshnuss** [comment]
@remiq Thanks!

Thinking about `standalone="no"`, do you think we need that?

Also, what happens if someone wants to use a different encoding than UTF-8, not sure how to handle that, thoughts?

**Comment by remiq** [comment]
@joshnuss According to specification (http://www.w3.org/TR/2004/REC-xml-20040204/#sec-rmd), `standalone` is optional and if not present, value is `no` by default, so it does not do anything.

Elixir strings are UTF-8 and I would not bother to handle other cases in my library, but if I would really have to, I would extend `def generate(:_doc_type, 0, encoding \\ "UTF-8")` and `def doc_enc(name_or_tuple, encoding)`.

**Comment by joshnuss** [comment]
Cool,

So let's leave `standalone='no'` out (since it's already the default).

And let's just hardcode UTF-8 for now, if someone needs a different encoding, they can provide a PR :smile_cat:

**Comment by remiq** [comment]
@joshnuss Updated.

**Comment by joshnuss** [comment]
Merged, Thanks @remiq!!

**Pull request merged**
