### PR TITLE
Add default formatter config and run `mix format`

### PR DESCRIPTION
**Pull request by alappe**

### CODE REVIEW

**Comment by alappe** [comment]
Hey Josh,

you probably have reasons for not doing this, but it would totally ease contributions if the code base would follow the default formatting used by new elixir projects.

So I thought I'd try it :)

**Comment by joshnuss** [comment]
Actually that would be super useful!

(The project pre-dates `mix format`, so never got around to setting it up :sweat_smile:)

**Comment by joshnuss** [comment]
Thanks @alappe !!

**Comment by alappe** [comment]
Again, thank *you* very much!

**Pull request merged**
