### PR TITLE
[SJC-152] Add missing special character encoding

### PR DESCRIPTION
**Pull request by tsubery**

### CODE REVIEW

**Comment by joshnuss** [comment]
@tsubery thank you!

**Comment by tsubery** [comment]
Thanks @joshnuss , Do you mind publishing a new release when you have time?

**Comment by joshnuss** [comment]
Hi Gal,

I plan to publish one in a few weeks, for now use GitHub master.

**Comment by tsubery** [comment]
Sure, thanks!

**Pull request merged**
